"""Criando tabelas inciais

Revision ID: fde7d9312648
Revises: 
Create Date: 2026-03-30 08:08:41.736569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde7d9312648'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genero',
    sa.Column('id_genero', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_genero'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('filme',
    sa.Column('id_filme', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('ano_lancamento', sa.Integer(), nullable=False),
    sa.Column('sinopse', sa.Text(), nullable=True),
    sa.Column('id_genero', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_genero'], ['genero.id_genero'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_filme')
    )
    op.create_table('avaliacao',
    sa.Column('id_avaliacao', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_filme', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.CheckConstraint('nota >= 1 AND nota <= 5', name='check_nota_range'),
    sa.ForeignKeyConstraint(['id_filme'], ['filme.id_filme'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_avaliacao'),
    sa.UniqueConstraint('id_usuario', 'id_filme', name='uk_usuario_filme')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacao')
    op.drop_table('filme')
    op.drop_table('usuario')
    op.drop_table('genero')
    # ### end Alembic commands ###
